language: ruby
sudo: false
rvm: 2.3.1
cache: bundler
bundler_args: "--without production development"
before_script:
- bundle exec rake db:create db:schema:load
- bundle exec rake db:test:prepare
- 'export DISPLAY=:99.0'
- 'sh -e /etc/init.d/xvfb start'
addons:
  postgresql: '9.4'
