language: ruby
sudo: false
rvm: 2.3.1
cache: bundler
bundler_args: "--without production development"
before_script:
- bundle exec rake db:create db:schema:load
- bundle exec rake db:test:prepare
addons:
  postgresql: '9.4'
env:
  global:
    secure: k+t6jILhd/nnaq8wf+dq9OsPtGwa15HC9JbhxqGQygIabyyXfFJK5pSdZymlj8iR7EDu8S6rlbMOx5WRBamTf7Ax8expCc3XJZDCs+4ipilZhmP2ts7IaCw0mNvGBzWUSKk+Lr23qOe7aGdU74hT+Madk2dckeXQ9yTte4hSqlHPR+siBJ5oCrQ1rgbnNaQIIlBhHr3R9Ryq6u2pkUnMka33KbvCPSNF1A/2rDS+5YQLfk7c00G2mhg0iBY3WYXhzonD5kfOsFbNLRNt8CQbWyBpqBnLQv1mDUub4N/7ks+WfYSmoT82crtxR2IG7UvL9wiqWQm4ATY/ihGJM/8owjvB8L6Md+lEczVzHPlPz8Mq34CGjhKP+ZDhZdm4aCnNm6s2xeT6MAcwxhtJG+1/l/1+va7hRl5ELrvW1hlXLkd2CzAHt6j5Qe685pk3XXACblhhAiCzlHw1i691fjnEt9Y5KvI1mmQLVlEiJQy1XngNKUpV2zT22Tg3vG0uHOfqo1+SYethEDyp1Dvy+L8vXO+FFkjLTeVOW7NAqVEyUcsx7ibsK3xhcOQBCCwUZ3+6aGNBGpolKaTagOB5jDmfdlRCO9PbNgXrypnLmOYvS2xO/YshU6s5sGZPS13o3jfEzpNUvsv80ufQ41NFoksfvUCyGxI6qpId5Ha6WkqCmUY=
