default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kengai_development

test:
  <<: *default
  database: kengai_test

production:
  <<: *default
  database: kengai_production
  username: kengai
  password: <%= ENV['KENGAI_DATABASE_PASSWORD'] %>
